#!/usr/bin/env python3
"""Translate amiga-runtime declarative profiles into FS-UAE configuration."""
import pathlib
import sys

if len(sys.argv) not in (6, 7):
    raise SystemExit("usage: generate-fs-uae-config.py PROFILE ROM EXT ISO OUTPUT [EVIDENCE_DIR]")

profile_path, rom, ext, iso, output = map(pathlib.Path, sys.argv[1:6])
evidence = pathlib.Path(sys.argv[6]) if len(sys.argv) == 7 else None
values = {}
for raw in profile_path.read_text().splitlines():
    line = raw.strip()
    if not line or line.startswith("#"):
        continue
    key, sep, value = line.partition("=")
    if not sep:
        raise SystemExit(f"invalid profile line: {raw}")
    values[key.strip()] = value.strip()

machines = {
    "a500": "A500",
    "a500plus": "A500+",
    "a1200": "A1200",
    "a4000": "A4000",
}
cpus = {"68000": "68000", "68020": "68020", "68030": "68030", "68040": "68040"}
try:
    model = machines[values["machine"]]
    cpu = cpus[values["cpu"]]
except KeyError as exc:
    raise SystemExit(f"unsupported profile value: {exc}")

chip_kib = int(values.get("chip_memory_kib", "2048"))
fast_kib = int(values.get("fast_memory_kib", "0"))
if chip_kib % 1024 or fast_kib % 1024:
    raise SystemExit("FS-UAE generator currently requires whole-MiB memory sizes")

lines = [
    "# Generated by amiga-runtime; do not edit.",
    f"amiga_model = {model}",
    f"cpu = {cpu}",
    f"chip_memory = {chip_kib // 1024}",
    f"fast_memory = {fast_kib // 1024}",
    f"kickstart_file = {rom}",
    f"kickstart_ext_file = {ext}",
    f"cdrom_drive_0 = {iso}",
    "console_debugger = 0",
]
if evidence is not None:
    lines.extend([
        f"hard_drive_0 = {evidence}",
        "hard_drive_0_label = Evidence",
        "hard_drive_0_read_only = 0",
        "hard_drive_0_priority = -10",
    ])
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("\n".join(lines) + "\n")
