#!/usr/bin/env python3
"""Translate amiga-runtime declarative profiles into FS-UAE configuration."""
import os
import pathlib
import sys

if len(sys.argv) not in (7, 8):
    raise SystemExit("usage: generate-fs-uae-config.py PROFILE ROM EXT ISO FLOPPY OUTPUT [EVIDENCE_DIR]")

profile_path, rom, ext, iso, floppy, output = map(pathlib.Path, sys.argv[1:7])
evidence = pathlib.Path(sys.argv[7]) if len(sys.argv) == 8 else None
values = {}
for raw in profile_path.read_text().splitlines():
    line = raw.strip()
    if not line or line.startswith("#"):
        continue
    key, sep, value = line.partition("=")
    if not sep:
        raise SystemExit(f"invalid profile line: {raw}")
    values[key.strip()] = value.strip()

machines = {"a500": "A500", "a500plus": "A500+", "a1200": "A1200", "a4000": "A4000"}
cpus = {"68000": "68000", "68020": "68020", "68030": "68030", "68040": "68040"}
try:
    model = machines[values["machine"]]
    cpu = cpus[values["cpu"]]
except KeyError as exc:
    raise SystemExit(f"unsupported profile value: {exc}")

chip_kib = int(values.get("chip_memory_kib", "2048"))
fast_kib = int(values.get("fast_memory_kib", "0"))
z3_kib = int(values.get("zorro_iii_memory_kib", "0"))
if chip_kib % 512:
    raise SystemExit("FS-UAE chip memory must be a multiple of 512 KiB")
if fast_kib % 1024:
    raise SystemExit("FS-UAE fast memory must be a multiple of 1024 KiB")
if z3_kib % 1024:
    raise SystemExit("FS-UAE Zorro III memory must be a multiple of 1024 KiB")

# For AROS directory-volume qualification, deliberately use the exact minimal
# FS-UAE configuration already proven by Ploos-AS/AmiGuard.  Machine tuning
# belongs to later profile qualification; this first gate proves that the
# redistributable m68k guest actually boots and executes Startup-Sequence.
if True:
    lines = [
        "# Generated by amiga-runtime; boot the official AROS m68k ISO directly.",
        "amiga_model = A1200",
        "kickstart_file = internal",
        f"cdrom_drive_0 = {iso}",
        "fullscreen = 0",
        "window_width = 640",
        "window_height = 512",
    ]

if evidence is not None:
    drive = 0
    lines.extend([
        f"hard_drive_{drive} = {evidence}",
    ])
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("\n".join(lines) + "\n")
